---
version: "3"
services:
  devopsdb:
    container_name: devopsdb
    build: ./Docker-db
    ports:
      - 2222:3306

  app:
    container_name: app
    build: ./Docker-app
    ports:
      - 3333:8080
